version: "3.9"

services:
  api:
    container_name: go-kit-2026-dev
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    ports:
      - "${APP_PORT:-8081}:8080"
    env_file:
      - ../../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: air


#   db:
#     image: mariadb:11
#     container_name: go-kit-2026-db
#     restart: unless-stopped
#     environment:
#       MARIADB_ROOT_PASSWORD: root
#       MARIADB_DATABASE: go_kit
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
